version: "3.9"

services:
  monarx:
    image: python:3.11-slim
    container_name: monarx_sentinel
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "pip install -e . && monarx-sentinel --watch"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  sandbox:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    container_name: monarx_sandbox
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    command: /bin/bash
